services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
    
    ports:
      - "5435":"5432"
    volumes:
      - db:/data/postgres
    network:
      - cicd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  cicd_test_project:
    build: .
    container_name: test_cicd
    ports:
      - "50051":"50051"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - cicd

networks:
  cicd:
    driver: bridge