name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 3.121.86.177
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            # Check if cicd directory exists, if not, create it
            mkdir -p $HOME/cicd
            
            # Check if lesson_ci_cd directory exists
            if [ ! -d "$HOME/cicd/lesson_ci_cd/.git" ]; then
              # Clone the repo if it does not exist
              git clone https://github.com/unknown3472/lesson_ci_cd.git $HOME/cicd/lesson_ci_cd
            else
              # Navigate to the lesson_ci_cd directory and pull the latest changes
              cd $HOME/cicd/lesson_ci_cd
              git pull origin main
            fi
            
            # Navigate to the lesson_ci_cd directory
            cd $HOME/cicd/lesson_ci_cd
            
            # Build and deploy using Docker Compose
            docker-compose up --build -d
          script_stop: true
          timeout: 200s
