name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 172-26-0-144

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "cicd" ]; then
              mkdir -p cicd
            fi
            cd cicd/lesson_ci_cd/
            docker compose down
            docker image rm lesson_ci_cd-cicd_test_project
            git pull origin main
            docker compose up -d
          script_stop: true
          timeout: 200s
      - name: Print SSH Key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 5  # Display the first few lines of the SSH key for debugging (be cautious with this in production)

      - name: Check SSH Key File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh-keygen -y -f /tmp/id_rsa
      - name: Create SSH Key File
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

      - name: Validate SSH Key
        run: ssh-keygen -y -f /tmp/id_rsa

